//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Requests
{
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class CreateTransactionRequest
    {

        /// <summary>
        /// The id of the budget. &quot;last-used&quot; can be used to specify the last used budget and &quot;default&quot; can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=budget_id")]
        public string BudgetId { get; set; } = default!;

        /// <summary>
        /// The transaction or transactions to create.  To create a single transaction you can specify a value for the `transaction` object and to create multiple transactions you can specify an array of `transactions`.  It is expected that you will only provide a value for one of these objects.
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=application/json")]
        public PostTransactionsWrapper PostTransactionsWrapper { get; set; } = default!;
    }
}