//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Requests
{
    using WalkerTX.Ynab.SDK.Utils;
    
    public class GetBudgetsRequest
    {

        /// <summary>
        /// Whether to include the list of budget accounts
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=include_accounts")]
        public bool? IncludeAccounts { get; set; }
    }
}