//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Requests
{
    using NodaTime;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class GetMonthCategoryByIdRequest
    {

        /// <summary>
        /// The id of the budget. &quot;last-used&quot; can be used to specify the last used budget and &quot;default&quot; can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=budget_id")]
        public string BudgetId { get; set; } = default!;

        /// <summary>
        /// The budget month in ISO format (e.g. 2016-12-01) (&quot;current&quot; can also be used to specify the current calendar month (UTC))
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=month")]
        public LocalDate Month { get; set; } = default!;

        /// <summary>
        /// The id of the category
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=category_id")]
        public string CategoryId { get; set; } = default!;
    }
}