//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Requests
{
    using NodaTime;
    using WalkerTX.Ynab.SDK.Models.Requests;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class GetTransactionsRequest
    {

        /// <summary>
        /// The id of the budget. &quot;last-used&quot; can be used to specify the last used budget and &quot;default&quot; can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=budget_id")]
        public string BudgetId { get; set; } = default!;

        /// <summary>
        /// If specified, only transactions on or after this date will be included.  The date should be ISO formatted (e.g. 2016-12-30).
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=since_date")]
        public LocalDate? SinceDate { get; set; }

        /// <summary>
        /// If specified, only transactions of the specified type will be included. &quot;uncategorized&quot; and &quot;unapproved&quot; are currently supported.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=type")]
        public GetTransactionsType? Type { get; set; }

        /// <summary>
        /// The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=last_knowledge_of_server")]
        public long? LastKnowledgeOfServer { get; set; }
    }
}