//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Requests
{
    using Newtonsoft.Json;
    using System;
    using WalkerTX.Ynab.SDK.Utils;
    
    /// <summary>
    /// If specified, only transactions of the specified type will be included. &quot;uncategorized&quot; and &quot;unapproved&quot; are currently supported.
    /// </summary>
    public enum GetTransactionsType
    {
        [JsonProperty("uncategorized")]
        Uncategorized,
        [JsonProperty("unapproved")]
        Unapproved,
    }

    public static class GetTransactionsTypeExtension
    {
        public static string Value(this GetTransactionsType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetTransactionsType ToEnum(this string value)
        {
            foreach(var field in typeof(GetTransactionsType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetTransactionsType)
                    {
                        return (GetTransactionsType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetTransactionsType");
        }
    }

}