//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Requests
{
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class UpdateTransactionsRequest
    {

        /// <summary>
        /// The id of the budget. &quot;last-used&quot; can be used to specify the last used budget and &quot;default&quot; can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=budget_id")]
        public string BudgetId { get; set; } = default!;

        /// <summary>
        /// The transactions to update. Each transaction must have either an `id` or `import_id` specified. If `id` is specified as null an `import_id` value can be provided which will allow transaction(s) to be updated by its `import_id`. If an `id` is specified, it will always be used for lookup.  You should not specify both `id` and `import_id`.  Updating an `import_id` on an existing transaction is not allowed; if an `import_id` is specified, it will only be used to lookup the transaction.
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=application/json")]
        public PatchTransactionsWrapper PatchTransactionsWrapper { get; set; } = default!;
    }
}