//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using WalkerTX.Ynab.SDK.Utils;
    
    /// <summary>
    /// The type of account
    /// </summary>
    public enum AccountType
    {
        [JsonProperty("checking")]
        Checking,
        [JsonProperty("savings")]
        Savings,
        [JsonProperty("cash")]
        Cash,
        [JsonProperty("creditCard")]
        CreditCard,
        [JsonProperty("lineOfCredit")]
        LineOfCredit,
        [JsonProperty("otherAsset")]
        OtherAsset,
        [JsonProperty("otherLiability")]
        OtherLiability,
        [JsonProperty("mortgage")]
        Mortgage,
        [JsonProperty("autoLoan")]
        AutoLoan,
        [JsonProperty("studentLoan")]
        StudentLoan,
        [JsonProperty("personalLoan")]
        PersonalLoan,
        [JsonProperty("medicalDebt")]
        MedicalDebt,
        [JsonProperty("otherDebt")]
        OtherDebt,
    }

    public static class AccountTypeExtension
    {
        public static string Value(this AccountType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AccountType ToEnum(this string value)
        {
            foreach(var field in typeof(AccountType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AccountType)
                    {
                        return (AccountType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AccountType");
        }
    }

}