//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class Account
    {

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// The type of account
        /// </summary>
        [JsonProperty("type")]
        public AccountType Type { get; set; } = default!;

        /// <summary>
        /// Whether this account is on budget or not
        /// </summary>
        [JsonProperty("on_budget")]
        public bool OnBudget { get; set; } = default!;

        /// <summary>
        /// Whether this account is closed or not
        /// </summary>
        [JsonProperty("closed")]
        public bool Closed { get; set; } = default!;

        [JsonProperty("note")]
        public string? Note { get; set; } = null;

        /// <summary>
        /// The current balance of the account in milliunits format
        /// </summary>
        [JsonProperty("balance")]
        public long Balance { get; set; } = default!;

        /// <summary>
        /// The current cleared balance of the account in milliunits format
        /// </summary>
        [JsonProperty("cleared_balance")]
        public long ClearedBalance { get; set; } = default!;

        /// <summary>
        /// The current uncleared balance of the account in milliunits format
        /// </summary>
        [JsonProperty("uncleared_balance")]
        public long UnclearedBalance { get; set; } = default!;

        /// <summary>
        /// The payee id which should be used when transferring to this account
        /// </summary>
        [JsonProperty("transfer_payee_id", NullValueHandling = NullValueHandling.Include)]
        public string? TransferPayeeId { get; set; }

        /// <summary>
        /// Whether or not the account is linked to a financial institution for automatic transaction import.
        /// </summary>
        [JsonProperty("direct_import_linked")]
        public bool? DirectImportLinked { get; set; }

        /// <summary>
        /// If an account linked to a financial institution (direct_import_linked=true) and the linked connection is not in a healthy state, this will be true.
        /// </summary>
        [JsonProperty("direct_import_in_error")]
        public bool? DirectImportInError { get; set; }

        /// <summary>
        /// A date/time specifying when the account was last reconciled.
        /// </summary>
        [JsonProperty("last_reconciled_at")]
        public DateTime? LastReconciledAt { get; set; } = null;

        /// <summary>
        /// This field is deprecated and will always be null.
        /// </summary>
        [JsonProperty("debt_original_balance")]
        public long? DebtOriginalBalance { get; set; } = null;

        [JsonProperty("debt_interest_rates")]
        public Dictionary<string, long>? DebtInterestRates { get; set; } = null;

        [JsonProperty("debt_minimum_payments")]
        public Dictionary<string, long>? DebtMinimumPayments { get; set; } = null;

        [JsonProperty("debt_escrow_amounts")]
        public Dictionary<string, long>? DebtEscrowAmounts { get; set; } = null;

        /// <summary>
        /// Whether or not the account has been deleted.  Deleted accounts will only be included in delta requests.
        /// </summary>
        [JsonProperty("deleted")]
        public bool Deleted { get; set; } = default!;
    }
}