//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class BudgetSettings
    {

        /// <summary>
        /// The date format setting for the budget.  In some cases the format will not be available and will be specified as null.
        /// </summary>
        [JsonProperty("date_format", NullValueHandling = NullValueHandling.Include)]
        public DateFormat? DateFormat { get; set; }

        /// <summary>
        /// The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
        /// </summary>
        [JsonProperty("currency_format", NullValueHandling = NullValueHandling.Include)]
        public CurrencyFormat? CurrencyFormat { get; set; }
    }
}