//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using NodaTime;
    using System;
    using System.Collections.Generic;
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class BudgetDetail
    {

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// The last time any changes were made to the budget from either a web or mobile client
        /// </summary>
        [JsonProperty("last_modified_on")]
        public DateTime? LastModifiedOn { get; set; }

        /// <summary>
        /// The earliest budget month
        /// </summary>
        [JsonProperty("first_month")]
        public LocalDate? FirstMonth { get; set; }

        /// <summary>
        /// The latest budget month
        /// </summary>
        [JsonProperty("last_month")]
        public LocalDate? LastMonth { get; set; }

        /// <summary>
        /// The date format setting for the budget.  In some cases the format will not be available and will be specified as null.
        /// </summary>
        [JsonProperty("date_format")]
        public DateFormat? DateFormat { get; set; } = null;

        /// <summary>
        /// The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
        /// </summary>
        [JsonProperty("currency_format")]
        public CurrencyFormat? CurrencyFormat { get; set; } = null;

        [JsonProperty("accounts")]
        public List<Account>? Accounts { get; set; }

        [JsonProperty("payees")]
        public List<Payee>? Payees { get; set; }

        [JsonProperty("payee_locations")]
        public List<PayeeLocation>? PayeeLocations { get; set; }

        [JsonProperty("category_groups")]
        public List<CategoryGroup>? CategoryGroups { get; set; }

        [JsonProperty("categories")]
        public List<Category>? Categories { get; set; }

        [JsonProperty("months")]
        public List<MonthDetail>? Months { get; set; }

        [JsonProperty("transactions")]
        public List<TransactionSummary>? Transactions { get; set; }

        [JsonProperty("subtransactions")]
        public List<SubTransaction>? Subtransactions { get; set; }

        [JsonProperty("scheduled_transactions")]
        public List<ScheduledTransactionSummary>? ScheduledTransactions { get; set; }

        [JsonProperty("scheduled_subtransactions")]
        public List<ScheduledSubTransaction>? ScheduledSubtransactions { get; set; }
    }
}