//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using WalkerTX.Ynab.SDK.Utils;
    
    /// <summary>
    /// The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
    /// </summary>
    public class CurrencyFormat
    {

        [JsonProperty("iso_code")]
        public string IsoCode { get; set; } = default!;

        [JsonProperty("example_format")]
        public string ExampleFormat { get; set; } = default!;

        [JsonProperty("decimal_digits")]
        public int DecimalDigits { get; set; } = default!;

        [JsonProperty("decimal_separator")]
        public string DecimalSeparator { get; set; } = default!;

        [JsonProperty("symbol_first")]
        public bool SymbolFirst { get; set; } = default!;

        [JsonProperty("group_separator")]
        public string GroupSeparator { get; set; } = default!;

        [JsonProperty("currency_symbol")]
        public string CurrencySymbol { get; set; } = default!;

        [JsonProperty("display_symbol")]
        public bool DisplaySymbol { get; set; } = default!;
    }
}