//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using WalkerTX.Ynab.SDK.Utils;
    
    /// <summary>
    /// The type of goal, if the category has a goal (TB=&apos;Target Category Balance&apos;, TBD=&apos;Target Category Balance by Date&apos;, MF=&apos;Monthly Funding&apos;, NEED=&apos;Plan Your Spending&apos;)
    /// </summary>
    public enum GoalType
    {
        [JsonProperty("TB")]
        Tb,
        [JsonProperty("TBD")]
        Tbd,
        [JsonProperty("MF")]
        Mf,
        [JsonProperty("NEED")]
        Need,
        [JsonProperty("DEBT")]
        Debt,
    }

    public static class GoalTypeExtension
    {
        public static string Value(this GoalType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GoalType ToEnum(this string value)
        {
            foreach(var field in typeof(GoalType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GoalType)
                    {
                        return (GoalType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GoalType");
        }
    }

}