//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Net.Http;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class HTTPMetadata
    {

        /// <summary>
        /// Raw HTTP response; suitable for custom response parsing
        /// </summary>
        [JsonProperty("-")]
        public HttpResponseMessage Response { get; set; } = default!;

        /// <summary>
        /// Raw HTTP request; suitable for debugging
        /// </summary>
        [JsonProperty("-")]
        public HttpRequestMessage Request { get; set; } = default!;
    }
}