//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using NodaTime;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class MonthSummary
    {

        [JsonProperty("month")]
        public LocalDate Month { get; set; } = default!;

        [JsonProperty("note")]
        public string? Note { get; set; } = null;

        /// <summary>
        /// The total amount of transactions categorized to &apos;Inflow: Ready to Assign&apos; in the month
        /// </summary>
        [JsonProperty("income")]
        public long Income { get; set; } = default!;

        /// <summary>
        /// The total amount budgeted in the month
        /// </summary>
        [JsonProperty("budgeted")]
        public long Budgeted { get; set; } = default!;

        /// <summary>
        /// The total amount of transactions in the month, excluding those categorized to &apos;Inflow: Ready to Assign&apos;
        /// </summary>
        [JsonProperty("activity")]
        public long Activity { get; set; } = default!;

        /// <summary>
        /// The available amount for &apos;Ready to Assign&apos;
        /// </summary>
        [JsonProperty("to_be_budgeted")]
        public long ToBeBudgeted { get; set; } = default!;

        /// <summary>
        /// The Age of Money as of the month
        /// </summary>
        [JsonProperty("age_of_money")]
        public int? AgeOfMoney { get; set; } = null;

        /// <summary>
        /// Whether or not the month has been deleted.  Deleted months will only be included in delta requests.
        /// </summary>
        [JsonProperty("deleted")]
        public bool Deleted { get; set; } = default!;
    }
}