//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class MonthSummariesResponseData
    {

        [JsonProperty("months")]
        public List<MonthSummary> Months { get; set; } = default!;

        /// <summary>
        /// The knowledge of the server
        /// </summary>
        [JsonProperty("server_knowledge")]
        public long ServerKnowledge { get; set; } = default!;
    }
}