//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class PayeeLocation
    {

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("payee_id")]
        public string PayeeId { get; set; } = default!;

        [JsonProperty("latitude")]
        public string Latitude { get; set; } = default!;

        [JsonProperty("longitude")]
        public string Longitude { get; set; } = default!;

        /// <summary>
        /// Whether or not the payee location has been deleted.  Deleted payee locations will only be included in delta requests.
        /// </summary>
        [JsonProperty("deleted")]
        public bool Deleted { get; set; } = default!;
    }
}