//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class SaveSubTransaction
    {

        /// <summary>
        /// The subtransaction amount in milliunits format.
        /// </summary>
        [JsonProperty("amount")]
        public long Amount { get; set; } = default!;

        /// <summary>
        /// The payee for the subtransaction.
        /// </summary>
        [JsonProperty("payee_id")]
        public string? PayeeId { get; set; } = null;

        /// <summary>
        /// The payee name.  If a `payee_name` value is provided and `payee_id` has a null value, the `payee_name` value will be used to resolve the payee by either (1) a matching payee rename rule (only if import_id is also specified on parent transaction) or (2) a payee with the same name or (3) creation of a new payee.
        /// </summary>
        [JsonProperty("payee_name")]
        public string? PayeeName { get; set; } = null;

        /// <summary>
        /// The category for the subtransaction.  Credit Card Payment categories are not permitted and will be ignored if supplied.
        /// </summary>
        [JsonProperty("category_id")]
        public string? CategoryId { get; set; } = null;

        [JsonProperty("memo")]
        public string? Memo { get; set; } = null;
    }
}