//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class SaveCategory
    {

        [JsonProperty("name")]
        public string? Name { get; set; } = null;

        [JsonProperty("note")]
        public string? Note { get; set; } = null;

        [JsonProperty("category_group_id")]
        public string? CategoryGroupId { get; set; }

        /// <summary>
        /// The goal target amount in milliunits format.  This amount can only be changed if the category already has a configured goal (goal_type != null).
        /// </summary>
        [JsonProperty("goal_target")]
        public long? GoalTarget { get; set; } = null;
    }
}