//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class SaveAccount
    {

        /// <summary>
        /// The name of the account
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// The type of account
        /// </summary>
        [JsonProperty("type")]
        public AccountType Type { get; set; } = default!;

        /// <summary>
        /// The current balance of the account in milliunits format
        /// </summary>
        [JsonProperty("balance")]
        public long Balance { get; set; } = default!;
    }
}