//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class SavePayee
    {

        /// <summary>
        /// The name of the payee. The name must be a maximum of 500 characters.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }
    }
}