//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class SaveTransactionsResponseData
    {

        /// <summary>
        /// The transaction ids that were saved
        /// </summary>
        [JsonProperty("transaction_ids")]
        public List<string> TransactionIds { get; set; } = default!;

        [JsonProperty("transaction")]
        public TransactionDetail? Transaction { get; set; }

        /// <summary>
        /// If multiple transactions were specified, the transactions that were saved
        /// </summary>
        [JsonProperty("transactions")]
        public List<TransactionDetail>? Transactions { get; set; }

        /// <summary>
        /// If multiple transactions were specified, a list of import_ids that were not created because of an existing `import_id` found on the same account
        /// </summary>
        [JsonProperty("duplicate_import_ids")]
        public List<string>? DuplicateImportIds { get; set; }

        /// <summary>
        /// The knowledge of the server
        /// </summary>
        [JsonProperty("server_knowledge")]
        public long ServerKnowledge { get; set; } = default!;
    }
}