//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using NodaTime;
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class SaveScheduledTransaction
    {

        [JsonProperty("account_id")]
        public string AccountId { get; set; } = default!;

        /// <summary>
        /// The scheduled transaction date in ISO format (e.g. 2016-12-01).  This should be a future date no more than 5 years into the future.
        /// </summary>
        [JsonProperty("date")]
        public LocalDate Date { get; set; } = default!;

        /// <summary>
        /// The scheduled transaction amount in milliunits format.
        /// </summary>
        [JsonProperty("amount")]
        public long? Amount { get; set; }

        /// <summary>
        /// The payee for the scheduled transaction.  To create a transfer between two accounts, use the account transfer payee pointing to the target account.  Account transfer payees are specified as `transfer_payee_id` on the account resource.
        /// </summary>
        [JsonProperty("payee_id")]
        public string? PayeeId { get; set; } = null;

        /// <summary>
        /// The payee name for the the scheduled transaction.  If a `payee_name` value is provided and `payee_id` has a null value, the `payee_name` value will be used to resolve the payee by either (1) a payee with the same name or (2) creation of a new payee.
        /// </summary>
        [JsonProperty("payee_name")]
        public string? PayeeName { get; set; } = null;

        /// <summary>
        /// The category for the scheduled transaction. Credit Card Payment categories are not permitted. Creating a split scheduled transaction is not currently supported.
        /// </summary>
        [JsonProperty("category_id")]
        public string? CategoryId { get; set; } = null;

        [JsonProperty("memo")]
        public string? Memo { get; set; } = null;

        /// <summary>
        /// The transaction flag
        /// </summary>
        [JsonProperty("flag_color")]
        public TransactionFlagColor? FlagColor { get; set; } = null;

        /// <summary>
        /// The scheduled transaction frequency
        /// </summary>
        [JsonProperty("frequency")]
        public ScheduledTransactionFrequency? Frequency { get; set; }
    }
}