//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using NodaTime;
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class ScheduledTransactionSummary
    {

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The first date for which the Scheduled Transaction was scheduled.
        /// </summary>
        [JsonProperty("date_first")]
        public LocalDate DateFirst { get; set; } = default!;

        /// <summary>
        /// The next date for which the Scheduled Transaction is scheduled.
        /// </summary>
        [JsonProperty("date_next")]
        public LocalDate DateNext { get; set; } = default!;

        [JsonProperty("frequency")]
        public ScheduledTransactionSummaryFrequency Frequency { get; set; } = default!;

        /// <summary>
        /// The scheduled transaction amount in milliunits format
        /// </summary>
        [JsonProperty("amount")]
        public long Amount { get; set; } = default!;

        [JsonProperty("memo")]
        public string? Memo { get; set; } = null;

        /// <summary>
        /// The transaction flag
        /// </summary>
        [JsonProperty("flag_color")]
        public TransactionFlagColor? FlagColor { get; set; } = null;

        /// <summary>
        /// The customized name of a transaction flag
        /// </summary>
        [JsonProperty("flag_name")]
        public string? FlagName { get; set; } = null;

        [JsonProperty("account_id")]
        public string AccountId { get; set; } = default!;

        [JsonProperty("payee_id")]
        public string? PayeeId { get; set; } = null;

        [JsonProperty("category_id")]
        public string? CategoryId { get; set; } = null;

        /// <summary>
        /// If a transfer, the account_id which the scheduled transaction transfers to
        /// </summary>
        [JsonProperty("transfer_account_id")]
        public string? TransferAccountId { get; set; } = null;

        /// <summary>
        /// Whether or not the scheduled transaction has been deleted.  Deleted scheduled transactions will only be included in delta requests.
        /// </summary>
        [JsonProperty("deleted")]
        public bool Deleted { get; set; } = default!;
    }
}