//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using WalkerTX.Ynab.SDK.Utils;
    
    public class ScheduledSubTransaction
    {

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("scheduled_transaction_id")]
        public string ScheduledTransactionId { get; set; } = default!;

        /// <summary>
        /// The scheduled subtransaction amount in milliunits format
        /// </summary>
        [JsonProperty("amount")]
        public long Amount { get; set; } = default!;

        [JsonProperty("memo")]
        public string? Memo { get; set; } = null;

        [JsonProperty("payee_id")]
        public string? PayeeId { get; set; } = null;

        [JsonProperty("payee_name")]
        public string? PayeeName { get; set; } = null;

        [JsonProperty("category_id")]
        public string? CategoryId { get; set; } = null;

        [JsonProperty("category_name")]
        public string? CategoryName { get; set; } = null;

        /// <summary>
        /// If a transfer, the account_id which the scheduled subtransaction transfers to
        /// </summary>
        [JsonProperty("transfer_account_id")]
        public string? TransferAccountId { get; set; } = null;

        /// <summary>
        /// Whether or not the scheduled subtransaction has been deleted. Deleted scheduled subtransactions will only be included in delta requests.
        /// </summary>
        [JsonProperty("deleted")]
        public bool Deleted { get; set; } = default!;
    }
}