//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using WalkerTX.Ynab.SDK.Utils;
    
    /// <summary>
    /// The cleared status of the transaction
    /// </summary>
    public enum TransactionClearedStatus
    {
        [JsonProperty("cleared")]
        Cleared,
        [JsonProperty("uncleared")]
        Uncleared,
        [JsonProperty("reconciled")]
        Reconciled,
    }

    public static class TransactionClearedStatusExtension
    {
        public static string Value(this TransactionClearedStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TransactionClearedStatus ToEnum(this string value)
        {
            foreach(var field in typeof(TransactionClearedStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TransactionClearedStatus)
                    {
                        return (TransactionClearedStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TransactionClearedStatus");
        }
    }

}