//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using WalkerTX.Ynab.SDK.Utils;
    
    /// <summary>
    /// The transaction flag
    /// </summary>
    public enum TransactionFlagColor
    {
        [JsonProperty("red")]
        Red,
        [JsonProperty("orange")]
        Orange,
        [JsonProperty("yellow")]
        Yellow,
        [JsonProperty("green")]
        Green,
        [JsonProperty("blue")]
        Blue,
        [JsonProperty("purple")]
        Purple,
        [JsonProperty("")]
        Unknown,
    }

    public static class TransactionFlagColorExtension
    {
        public static string Value(this TransactionFlagColor value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TransactionFlagColor ToEnum(this string value)
        {
            foreach(var field in typeof(TransactionFlagColor).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TransactionFlagColor)
                    {
                        return (TransactionFlagColor)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TransactionFlagColor");
        }
    }

}