//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WalkerTX.Ynab.SDK.Models.Errors
{
    using Newtonsoft.Json;
    using System;
    using System.Net.Http;
    using WalkerTX.Ynab.SDK.Models.Components;
    using WalkerTX.Ynab.SDK.Utils;

    public class ErrorResponsePayload
    {
        [JsonProperty("error")]
        public ErrorDetail Error { get; set; } = default!;

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }

    public class ErrorResponse : YnabException
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public ErrorResponsePayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use ErrorResponse.Payload.Error instead.")]
        public ErrorDetail Error { get; set; } = default!;

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use ErrorResponse.Payload.HttpMeta instead.")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        public ErrorResponse(
            ErrorResponsePayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ): base("API error occurred", request, response, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           Error = payload.Error;
           HttpMeta = payload.HttpMeta;
           #pragma warning restore CS0618
        }
    }

}